#pragma once

#include <string>
#include <vector>

namespace Labels {
    const std::vector<std::string> CAR_MODEL_LABELS{
            "Acura_MDX",
            "Audi_100",
            "Audi_80",
            "Audi_A4",
            "Audi_A6",
            "Audi_A8",
            "Audi_Q7",
            "BMW_3-Series",
            "BMW_5-Series",
            "BMW_7-Series",
            "BMW_X-Series",
            "Cadillac_Escalade",
            "Chevrolet_Aveo",
            "Chevrolet_Captiva",
            "Chevrolet_Corvette",
            "Chevrolet_Cruze",
            "Chevrolet_Lacetti",
            "Chevrolet_Niva",
            "Chevrolet_Orlando",
            "Daewoo_Gentra",
            "Daewoo_Magnus",
            "Daewoo_Matiz",
            "Daewoo_Nexia",
            "Datsun_on-DO",
            "Ford_Escape",
            "Ford_Explorer",
            "Ford_Focus",
            "Ford_Mondeo",
            "GAZ_3110 (Volga)",
            "GAZ_GAZel",
            "GAZ_Sobol",
            "Geely_GC7",
            "Geely_SC7",
            "Honda_Accord",
            "Honda_CR-V",
            "Honda_Civic",
            "Honda_HR-V",
            "Hummer_H2",
            "Hyundai_Accent/Solaris",
            "Hyundai_Atos",
            "Hyundai_Avante",
            "Hyundai_Azera",
            "Hyundai_Centennial",
            "Hyundai_Click",
            "Hyundai_Coupe",
            "Hyundai_Creta",
            "Hyundai_Elantra",
            "Hyundai_Equus",
            "Hyundai_Galloper",
            "Hyundai_Genesis",
            "Hyundai_Getz",
            "Hyundai_Grace",
            "Hyundai_Grandeur",
            "Hyundai_H 100",
            "Hyundai_H 350",
            "Hyundai_H-1",
            "Hyundai_Lantra",
            "Hyundai_Lavita",
            "Hyundai_Marcia",
            "Hyundai_Matrix",
            "Hyundai_Porter",
            "Hyundai_Santa Fe",
            "Hyundai_Sonata",
            "Hyundai_Starex",
            "Hyundai_Terracan",
            "Hyundai_Tiburon",
            "Hyundai_Trajet",
            "Hyundai_Tucson",
            "Hyundai_Tuscani",
            "Hyundai_Veloster",
            "Hyundai_Veracruz",
            "Hyundai_Verna",
            "Hyundai_i20",
            "Hyundai_i30",
            "Hyundai_i40",
            "Hyundai_ix35",
            "Infiniti_FX35",
            "Infiniti_FX45",
            "Infiniti_I30",
            "Infiniti_QX56",
            "Infiniti_QX70",
            "Infiniti_QX80",
            "JAC_S3",
            "JAC_S5",
            "Jaguar_S-Type",
            "Jaguar_XF",
            "Jaguar_XJ",
            "Jeep_Grand Cherokee",
            "Kia_Avella",
            "Kia_Bongo",
            "Kia_Cadenza",
            "Kia_Carens",
            "Kia_Carnival",
            "Kia_Ceed",
            "Kia_Cerato",
            "Kia_Credos",
            "Kia_Forte",
            "Kia_Joice",
            "Kia_K5",
            "Kia_K7",
            "Kia_Lotze",
            "Kia_Magentis",
            "Kia_Mohave",
            "Kia_Morning",
            "Kia_Opirus",
            "Kia_Optima",
            "Kia_Picanto",
            "Kia_Potencia",
            "Kia_Pride",
            "Kia_Quoris",
            "Kia_Retona",
            "Kia_Rio",
            "Kia_Sephia",
            "Kia_Shuma",
            "Kia_Sorento",
            "Kia_Soul",
            "Kia_Spectra",
            "Kia_Sportage",
            "Land Rover_Range Rover",
            "Lexus_ES-Series",
            "Lexus_GS-Series",
            "Lexus_GX-Series",
            "Lexus_HS-Series",
            "Lexus_IS-Series",
            "Lexus_LS-Series",
            "Lexus_LX-Series",
            "Lexus_NX-Series",
            "Lexus_RC-series",
            "Lexus_RX-Series",
            "Lexus_UX-Series",
            "Lincoln_Town Car",
            "Maserati_Levante",
            "Mazda_3",
            "Mazda_323",
            "Mazda_6",
            "Mazda_626",
            "Mazda_CX-5",
            "Mazda_CX-7",
            "Mazda_Xedos 6",
            "Mazda_Xedos 9",
            "Mercedes-Benz_A-Class",
            "Mercedes-Benz_AMG GT",
            "Mercedes-Benz_B-Class",
            "Mercedes-Benz_C-Class",
            "Mercedes-Benz_CE-Class",
            "Mercedes-Benz_CL-Class",
            "Mercedes-Benz_CLA-Class",
            "Mercedes-Benz_CLK-Class",
            "Mercedes-Benz_CLS-Class",
            "Mercedes-Benz_E-Class",
            "Mercedes-Benz_G-Class",
            "Mercedes-Benz_GL-Class",
            "Mercedes-Benz_GLA-Class",
            "Mercedes-Benz_GLC-Class",
            "Mercedes-Benz_GLE-Class",
            "Mercedes-Benz_GLK-Class",
            "Mercedes-Benz_GLS-Class",
            "Mercedes-Benz_ML-Class",
            "Mercedes-Benz_R-Class",
            "Mercedes-Benz_S-Class",
            "Mercedes-Benz_SL-Class",
            "Mercedes-Benz_SLK-Class",
            "Mercedes-Benz_Sprinter",
            "Mercedes-Benz_V-Class",
            "Mercedes-Benz_Vaneo",
            "Mercedes-Benz_Vario",
            "Mercedes-Benz_Viano",
            "Mercedes-Benz_Vito",
            "Mercedes-Maybach_S-Class",
            "Mitsubishi_Asx",
            "Mitsubishi_Carisma",
            "Mitsubishi_Galant",
            "Mitsubishi_Lancer",
            "Mitsubishi_Montero",
            "Mitsubishi_Outlander",
            "Mitsubishi_Pajero",
            "Mitsubishi_Space Gear",
            "Mitsubishi_Space Runner",
            "Nissan_Almera",
            "Nissan_Almera Classic",
            "Nissan_Almera Tino",
            "Nissan_Altima",
            "Nissan_Armada",
            "Nissan_Avenir",
            "Nissan_Bluebird",
            "Nissan_Caravan",
            "Nissan_Cedric",
            "Nissan_Cefiro",
            "Nissan_Cube",
            "Nissan_Elgrand",
            "Nissan_Expert",
            "Nissan_Frontier",
            "Nissan_Gloria",
            "Nissan_Juke",
            "Nissan_Largo",
            "Nissan_Laurel",
            "Nissan_Liberty",
            "Nissan_March",
            "Nissan_Maxima",
            "Nissan_Micra",
            "Nissan_Mistral",
            "Nissan_Murano",
            "Nissan_NP300",
            "Nissan_Navara",
            "Nissan_Note",
            "Nissan_Pathfinder",
            "Nissan_Patrol",
            "Nissan_Pixo",
            "Nissan_Prairie",
            "Nissan_Presage",
            "Nissan_Presea",
            "Nissan_Primera",
            "Nissan_Pulsar",
            "Nissan_Qashqai",
            "Nissan_Quest",
            "Nissan_Rogue",
            "Nissan_Safari",
            "Nissan_Sentra",
            "Nissan_Serena",
            "Nissan_Silvia",
            "Nissan_Skyline",
            "Nissan_Stagea",
            "Nissan_Sunny",
            "Nissan_Teana",
            "Nissan_Terrano",
            "Nissan_Terrano II",
            "Nissan_Tiida",
            "Nissan_Tino",
            "Nissan_Titan",
            "Nissan_Urvan",
            "Nissan_Vanette",
            "Nissan_Versa",
            "Nissan_X-Trail",
            "Nissan_Xterra",
            "Opel_Astra",
            "Opel_Vectra",
            "Peugeot_301",
            "Peugeot_307",
            "Peugeot_407",
            "Porsche_Cayenne",
            "Porsche_Panamera",
            "Ravon_Nexia",
            "Renault_Duster",
            "Renault_Kangoo",
            "Renault_Laguna",
            "Renault_Logan",
            "Renault_Sandero",
            "Renault_Scenic",
            "Scion_XD",
            "Skoda_Octavia",
            "Skoda_Rapid",
            "Skoda_Superb",
            "Skoda_Yeti",
            "SsangYong_Chairman",
            "SsangYong_Istana",
            "SsangYong_Kyron",
            "Subaru_Forester",
            "Subaru_Impreza",
            "Subaru_Legacy",
            "Subaru_Outback",
            "Subaru_XV",
            "Suzuki_Grand Vitara",
            "Toyota_4Runner",
            "Toyota_Alphard",
            "Toyota_Altezza",
            "Toyota_Aristo",
            "Toyota_Auris",
            "Toyota_Avalon",
            "Toyota_Avensis",
            "Toyota_Avensis Verso",
            "Toyota_Aygo",
            "Toyota_Caldina",
            "Toyota_Camry",
            "Toyota_Camry Lumiere",
            "Toyota_Carina",
            "Toyota_Carina E",
            "Toyota_Carina II",
            "Toyota_Celica",
            "Toyota_Celsior",
            "Toyota_Century",
            "Toyota_Chaser",
            "Toyota_Corolla",
            "Toyota_Corolla Verso",
            "Toyota_Corona",
            "Toyota_Corona Exiv",
            "Toyota_Cresta",
            "Toyota_Crown",
            "Toyota_Crown Majesta",
            "Toyota_Curren",
            "Toyota_Echo",
            "Toyota_Estima",
            "Toyota_Estima Emina",
            "Toyota_Estima Lucida",
            "Toyota_FJ Cruiser",
            "Toyota_Fortuner",
            "Toyota_Gaia",
            "Toyota_Harrier",
            "Toyota_HiAce",
            "Toyota_HiAce Regius",
            "Toyota_Highlander",
            "Toyota_Hilux",
            "Toyota_Hilux Surf",
            "Toyota_Ipsum",
            "Toyota_Land Cruiser",
            "Toyota_Land Cruiser 70",
            "Toyota_Land Cruiser Prado",
            "Toyota_MR 2",
            "Toyota_Mark II",
            "Toyota_Mark II Qualis",
            "Toyota_Matrix",
            "Toyota_Picnic",
            "Toyota_Previa",
            "Toyota_Prius",
            "Toyota_RAV 4",
            "Toyota_Scepter",
            "Toyota_Sequoia",
            "Toyota_Sienna",
            "Toyota_Soarer",
            "Toyota_Solara",
            "Toyota_Spacio",
            "Toyota_Sprinter",
            "Toyota_Sprinter Carib",
            "Toyota_Sprinter Marino",
            "Toyota_Starlet",
            "Toyota_Tercel",
            "Toyota_Town Ace",
            "Toyota_Town Ace Noah",
            "Toyota_Tundra",
            "Toyota_Venza",
            "Toyota_Verossa",
            "Toyota_Vista",
            "Toyota_Vista Ardeo",
            "Toyota_Vitz",
            "Toyota_Voxy",
            "Toyota_Windom",
            "Toyota_Yaris",
            "VAZ (Lada)_Kalina",
            "VAZ (Lada)_Zhiguli",
            "VAZ (Lada)_Samara (Satelite)",
            "VAZ (Lada)_110",
            "VAZ (Lada)_Samara 2",
            "VAZ (Lada)_Niva",
            "VAZ (Lada)_Priora",
            "VAZ (Lada)_Granta",
            "VAZ (Lada)_Largus",
            "VAZ (Lada)_Vesta",
            "VAZ (Lada)_XRAY",
            "Volkswagen_Amarok",
            "Volkswagen_Beetle",
            "Volkswagen_Bora",
            "Volkswagen_Caddy",
            "Volkswagen_Caravelle",
            "Volkswagen_Crafter",
            "Volkswagen_Eos",
            "Volkswagen_Eurovan",
            "Volkswagen_Gol",
            "Volkswagen_Golf",
            "Volkswagen_Golf Plus",
            "Volkswagen_Jetta",
            "Volkswagen_LT",
            "Volkswagen_Multivan",
            "Volkswagen_Passat",
            "Volkswagen_Phaeton",
            "Volkswagen_Polo",
            "Volkswagen_Santana",
            "Volkswagen_Sharan",
            "Volkswagen_Teramont",
            "Volkswagen_Tiguan",
            "Volkswagen_Touareg",
            "Volkswagen_Touran",
            "Volkswagen_Transporter",
            "Volkswagen_Vento",
            "Zaz_Chance",
            "Zaz_Forza",
            "Vanhool_Bus",
            "Hyundai_Bus",
            "Golaz_Bus",
            "Yutong_Bus",
            "Man_Bus",
            "Temsa_Bus",
            "Volvo_Bus",
            "Paz_Bus",
            "Maz_Bus",
            "Higer_Bus",
            "Daewoo_Bus",
            "Golden dragon_Bus",
            "Liaz_Bus",
            "Iveco_Bus",
            "Howo_Truck",
            "Zil_Truck",
            "China_Truck",
            "Scania_Truck",
            "Isuzu_Truck",
            "Iveco_Truck",
            "Foton_Truck",
            "Renault_Truck",
            "GAZ_Truck",
            "Jac_Truck",
            "Daf_Truck",
            "Man_Truck",
            "Hino_Truck",
            "Volvo_Truck",
            "Dongfeng_Truck",
            "Mitsubishi_Truck",
            "Maz_Truck",
            "Shacman_Truck",
            "Mercedes-Benz_Truck",
            "Kamaz_Kamaz",
            "Toyota_Coaster",
            "GAZ_Next",
            "Scania_Omnlink",
            "Uaz_Uaz",
            "Nissan_Condor",
            "Hyundai_Hd",
            "Nissan_Civilian",
            "Boschung_Jetbroom",
            "Ford_Cargo"
    };

    const std::vector<std::string> CAR_COLOR_LABELS = {
            "white",
            "blue",
            "black",
            "gray",
            "beige",
            "red",
            "light blue",
            "green",
            "brown",
            "violet",
            "burgundy",
            "yellow",
            "orange"
    };
}